-- AlterTable
ALTER TABLE "JobApplication" ADD COLUMN     "location" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "salary" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
